name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送以 'v' 开头的标签时触发

jobs:
  build:
    runs-on: windows-latest # 选择 Windows 环境，因为你使用了 cx_Freeze

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 指定你的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze

      - name: Build executable
        run: python setup.py build

      - name: Create release archive
        run: |
          Compress-Archive -Path build/exe.win-amd64/* -DestinationPath release.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release.zip
          asset_name: WeChat_Notifier.zip
          asset_content_type: application/zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false